### ISSUE TITLE
Problem with md4ws.msi

### ISSUE THREAD

**Issue by McZeb** [microsoft/mdefordownlevelserver#10]
I've an issue with the Install.ps1. When Defender (md4ws.msi) is to be installed with msiexec, I get the help for msiexec instead and the installation is interrupted. Any help would be appreciated.

![Windows Installer](https://user-images.githubusercontent.com/102311800/159956048-28540282-43f2-428e-91cb-c9362927bda9.png)

**Comment by pahuijbr** [comment]
We could not get a repro for this. Please try again with the latest version of the MSI and the script.
