### ISSUE TITLE
Wrong KB download during depency resolution?

### ISSUE THREAD

**Issue by fgondorf** [microsoft/mdefordownlevelserver#12]
Hello,
It appears that during the resolution of dependencies for Windows Server 2012R2, a standalone update package for an older Windows version gets downloaded.

Compare the downloaded file in line 346
`Windows8.1-KB2999226-x64.msu`

to the file referenced in line 350
`Windows6.1-KB3080149-x64.msu`

The download link in line 350 downloads a 17MB file intended for Windows 7 and Server 2008R2, neither of which are supported by the agent installed by this script. Running this update package on a Server 2012R2 results in a "not applicable" error.

According to the [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB3080149), the correct update package for KB3080149 for Windows Server 2012R2 (and Windows 8.1) is:

[windows8.1-kb3080149-x64](https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/updt/2015/08/windows8.1-kb3080149-x64_4254355747ba7cf6974bcfe27c4c34a042e3b07e.msu) 

and is 1.2 Megabytes in size.

I hope I'm not barking up the wrong tree here, but if this was indeed an error, I would be happy to see a fix, because the script is very useful for MDE deployments to older servers.

Thanks for your work.

**Comment by synssins** [comment]
I can confirm that using the KB you specified above for 2012r2/8.1 resolved an issue in which the KB specified in the script would try to install and then state that it was not applicable, leading to a failure in the installation.
Updating the URL in the script to point to the KB specified worked reliably on multiple systems.

We're just starting our deployment and onboarding of MDE in a 12k+ system environment.

**Comment by pahuijbr** [comment]
Investigating

**Comment by pahuijbr** [comment]
https://github.com/microsoft/mdefordownlevelserver/commit/a3d7b47a7aa2ca23209beac13b1a735458a745b0

**Comment by fgondorf** [comment]
@pahuijbr the issue is now closed but no change was made to the URL. I am still positive that a KB intended for 6.1 does not function on an OS 8.1 or newer. Why was this closed?

**Comment by pahuijbr** [comment]
@fgondorf thanks - please check the new version that was just uploaded
