### ISSUE TITLE
Please review the criteria for applying KB3080149 and KB2999226.

### ISSUE THREAD

**Issue by KENJISHIRAKI** [microsoft/mdefordownlevelserver#14]
Hello,

The script checks to see if KB3080149 and KB2999226 have been applied to the server and installs them if not. The following Docs show that there are no other prerequisites as long as the latest monthly rollup package is applied.
Therefore, is it possible to fix it so that KB3080149 and KB2999226 are not applied in environments where the latest monthly rollup package has been applied?
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide#windows-server-2012-r2-and-windows-server-2016
>If you have fully updated your machines with the latest monthly rollup package, there are no additional prerequisites.

I have an additional question: when do you expect to fix #8 and #12?
I have confirmed the above trouble in my environment, and if I modify the script myself, I get an error in the digital signature, this time because the hash is changed.
(I was able to avoid the signature error by setting ExecutionPolicy to bypass.)
Unfortunately, install.ps1 does not work as expected without some modifications on the part of the user, which is a problem for many users.

Best regards,

**Comment by pahuijbr** [comment]
Hi, the script checks the (versions of) the files before checking if a KB is already installed. If both are false it proceeds to attempt to download and updates.

The script is indeed signed, if you wish to test a modified version you should remove the signature.

We will investigate the KB issue mentioned in #12. However, as you mentioned, if the machine is up to date then this prerequisite should be met already.

**Comment by KENJISHIRAKI** [comment]
Thank you for your reply.
I understand the specification to download the KB in install.ps1.
Please continue to correct the URL in #12.

**Comment by pahuijbr** [comment]
https://github.com/microsoft/mdefordownlevelserver/commit/a3d7b47a7aa2ca23209beac13b1a735458a745b0
