### ISSUE TITLE
2012R2 Onboarding Issue

### ISSUE THREAD

**Issue by PehDeh** [microsoft/mdefordownlevelserver#17]
On a 2012R2 Server, Installation works great but the onboarding failed with error 15. 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-onboarding?view=o365-worldwide

Sense didn´t start.
Waited shortly and reran it. In the meantime kb2267602 was installed.
Sense started working.

Maybe it took longer and you should implement a timeout before running the onboarding?

After Reboot these Updates were available via WSUS
![grafik](https://user-images.githubusercontent.com/24938476/179914112-80b962e7-5e27-4d7a-9d1e-60e421bf120c.png)

```
C:\Windows\TEMP\fc12dd90-c33e-4d2e-8376-8eac2ce85853.log /quiet FORCEPASSIVEMODE=1" run for 00:02:05.7346912 [SERVERNAME:03 22.07.20T08:20:39.310 Install.ps1:934] install successful. 
[SERVERNAME:03 22.07.20T08:20:39.311 Install.ps1:940] Invoking onboarding script .\WindowsDefenderATPOnboardingScript.CMD 
[SERVERNAME:03 22.07.20T08:20:39.317 Install.ps1:948] Running C:\Windows\system32\cmd.exe /c .\WindowsDefenderATPOnboardingScript.CMD in C:\temp\DefenderOnboarding\2012R2and2016\mdefordownlevelserver-main ... 
[SERVERNAME:03 22.07.20T08:21:33.446 Install.ps1:948] Command "cmd.exe /c .\WindowsDefenderATPOnboardingScript.CMD" failed with error 0xf after 00:00:53.1039919 
[SERVERNAME:03 22.07.20T08:21:33.467 Install.ps1:952] **WARNING: Onboarding script returned 15** [SERVERNAME:03 22.07.20T08:21:33.473 Install.ps1:959] Closing handle 5268 
[SERVERNAME:03 22.07.20T08:21:33.595 Install.ps1:966] Tracing session 'install-SERVERNAME-6.3.9600.20475' stopped. 
[SERVERNAME:03 22.07.20T08:21:33.610 Install.ps1:970] ETL file: 'C:\temp\DefenderOnboarding\2012R2and2016\mdefordownlevelserver-main\install-SERVERNAME-6.3.9600.20475.etl'. 
[SERVERNAME:03 22.07.20T08:21:33.614 Install.ps1:975] Msi log: 'C:\temp\DefenderOnboarding\2012R2and2016\mdefordownlevelserver-main\install-SERVERNAME-6.3.9600.20475.log'
```

**Comment by pahuijbr** [comment]
Thanks for the feedback. KB2267602 (security intelligence update) should have no impact on Sense - please try the latest MSI package downloaded from the onboarding section of the portal - this contains 4.18.2205.7 antimalware platform.

Onboarding is expected to work without a timeout, but that said, your system may have been under heavy load preventing first service start from completing in a timely fashion after applying the onboarding information. A subsequent service start should still work. Without more information we can only speculate however!
