### ISSUE TITLE
Server2012r2 - MDE Install issue - @C;\Program Files\Windows Defender\MpAsDesc.dll,-310' (WinDefend)

### ISSUE THREAD

**Issue by insertacoolnamehere** [microsoft/mdefordownlevelserver#19]
Hi,

On our Server2012r2 fleet, when trying to deploy MDE we receive
"@C;\Program Files\Windows Defender\MpAsDesc.dll,-310' (WinDefend)".

This issue happens whether we run it manually or with the install.ps1 script. The install.ps1 script reports back 1603 error (which is a general error for the above more specific errror.

We seeing this on 5 (out of 5 so far), but we have a fleet of 400 to deploy this too.

Servers are fully patched. 

It's worth noting that before the MDE installer has been run there is no existing "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDefend" key.

This can be worked around by deleting “HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDefend” , rebooting, attemping to install again, deleting the “HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDefend” key AGAIN, then rebooting then the install works fine.

My observations seem to show the installer needs to be run twice, and cleaned up manually, and rebooted between this before working.

I've got a MS case open, but hoping to spread the word / find others with this issue

**Comment by yllekz** [comment]
This was my experience as well for 2012 R2 (except even with the workarounds, it still did not work). Honestly though, this workaround is not good enough as it requires multiple reboots on production systems along with somewhat unsettling registry key deletions. I really hope this can be fixed in a cleaner manner by Microsoft.

**Comment by pahuijbr** [comment]
We have identified an issue on some machines, introduced recently to the OS, that introduces a long delay in the MSI setup process causing a timeout of the first service start. Even though the install.ps1 script attempts to recover from the failed state, it's likely the machine hits this issue again as you have experienced.

We will be releasing a fixed MSI package as soon as possible.

**Comment by pahuijbr** [comment]
The updated MSI was released yesterday, containing the fix for this issue. Please download the latest package from the onboarding section of the portal. The script should help overcome previously failed installations.

**Comment by AbeSolis** [comment]
Hi @pahuijbr , I'm currently receiving this error with the latest MSI downloaded from the portal. The MSI creation date is 8/25/2022. Is there anything else I should be doing or do you know if i may have the wrong MSI based on the creation date?

> The updated MSI was released yesterday, containing the fix for this issue. Please download the latest package from the onboarding section of the portal. The script should help overcome previously failed installations.
