### ISSUE TITLE
OSversion returned to script incorrectly

### ISSUE THREAD

**Issue by NeverHere** [microsoft/mdefordownlevelserver#2]
We noticed this script returns the incorrect version number for servers that have been updated from 2012 to 2012 R2, while dism and registry report 6.3 the system variable being pulled in the script finds 6.2. Should the script read the registry at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion to more reliably return OS version?

**Comment by James3UK** [comment]
Deploying this script with ManageEngine returns "Unsupported OS version: 0.0.0.0" it appears fine when run manually.

Two ways to fix this, both reliant on the "UBR" registry value for the revision so option 1 is probably better (get it all from the registry):


```
$osRegkeys = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'
$osVerObj = New-Object System.Version $($osRegkeys.CurrentMajorVersionNumber), $($osRegkeys.CurrentMinorVersionNumber), $($osRegkeys.CurrentBuild), $($osRegkeys.UBR)
```

```
$osRegkeys = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'
$osVerWMI = (Get-CimInstance Win32_OperatingSystem).version.split('.')
$osVerObj = New-Object System.Version $($osVerWMI[0]), $($osVerWMI[1]), $($osVerWMI[2]), $($osRegkeys.UBR)
```
