### ISSUE TITLE
[Server 2016] Script hangs and never completes

### ISSUE THREAD

**Issue by yllekz** [microsoft/mdefordownlevelserver#21]
On Server 2016 I'm running the script as instructed but it never completes. See output below:

* Git repo is cloned to c:\windows\temp
* WindowsDefenderATPLocalOnboardScript.cmd was downloaded from security.microsoft.com via Settings->Onboarding and placed in c:\windows\temp\mdefordownlevelserver
* *md4ws.msi downloaded from security.microsoft.com via Settings->Onboarding and placed in c:\windows\temp\mdefordownlevelserver

Install line (PowerShell, as administrator):

``& "c:\windows\temp\mdefordownlevelserver\Install.ps1" -RemoveMMA '<MMA ID REDACTED>' -OnboardingScript "C:\windows\temp\mdefordownlevelserver\WindowsDefenderATPLocalOnboardingScript.cmd"``

Log output (it just hangs a minute in):

```
[PCNAME:09 22/08/11T13:48:50.107 Install.ps1:503] [Net.ServicePointManager]::SecurityProtocol updated to 'Ssl3, Tls, Tls12'
[PCNAME:09 22/08/11T13:48:50.622 Install.ps1:613] Tracing session 'install-PCNAME-10.0.14393.5246' started.
[PCNAME:09 22/08/11T13:48:50.794 Install.ps1:629] Removing cloud workspace <ID REDACTED>...
[PCNAME:09 22/08/11T13:48:51.138 Install.ps1:637] Workspace <ID REDACTED> removed.
[PCNAME:09 22/08/11T13:48:51.203 Install.ps1:657] BuildLabEx: 14393.5246.amd64fre.rs1_release.220701-1744
[PCNAME:09 22/08/11T13:48:54.047 Install.ps1:660] There are 27 KBs installed.
[PCNAME:09 22/08/11T13:48:54.047 Install.ps1:663] KB5016058 was installed on 08/10/2022 00:00:00
[PCNAME:09 22/08/11T13:48:56.956 Install.ps1:286] 'HKCR' PSDrive created(script scoped)
[PCNAME:09 22/08/11T13:48:57.800 Install.ps1:961] Handle 3248 opened over C:\windows\temp\mdefordownlevelserver\md4ws.msi
[PCNAME:09 22/08/11T13:49:00.550 Install.ps1:972] 797261D33CB9160051DE3F2AFA691C63A5078ED8724A56A3322E4DE846DDCFA3 C:\windows\temp\mdefordownlevelserver\md4ws.msi
[PCNAME:09 22/08/11T13:49:00.597 Install.ps1:996] Running C:\Windows\system32\msiexec.exe /i C:\windows\temp\mdefordownlevelserver\md4ws.msi /lvx*+ C:\Users\<NAME REDACTED>\AppData\Local\Temp\8fe4e3b3-7114-4144-b31d-0fd0fcc888b2.log /quiet in C:\Windows\system32 ...
[PCNAME:09 22/08/11T13:49:05.727 Install.ps1:996] Command "msiexec.exe /i C:\windows\temp\mdefordownlevelserver\md4ws.msi /lvx*+ C:\Users\<NAME REDACTED>\AppData\Local\Temp\8fe4e3b3-7114-4144-b31d-0fd0fcc888b2.log /quiet" run for 00:00:04.7665445
[PCNAME:09 22/08/11T13:49:05.743 Install.ps1:998] install successful.
[PCNAME:09 22/08/11T13:49:05.743 Install.ps1:1020] Invoking onboarding script C:\windows\temp\mdefordownlevelserver\WindowsDefenderATPLocalOnboardingScript.cmd
[PCNAME:09 22/08/11T13:49:05.759 Install.ps1:1028] Running C:\Windows\system32\cmd.exe /c C:\windows\temp\mdefordownlevelserver\WindowsDefenderATPLocalOnboardingScript.cmd in C:\Windows\system32 ...
#30+ minutes pass, nothing happens past this point.
```

The temp log file states it successfully installed the "Microsoft Defender for Endpoint" application but seems to have ceased all activity afterwards. The "Sense" service did not start and errors out when I attempt to manually start it.

What could the issue be? Task manager is quiet and there's little indication of what is happening.

**Comment by pahuijbr** [comment]
Hi, you are using WindowsDefenderATPLocalOnboardingScript.cmd which is interactive (requires user input). Please use the onboarding script for use with group policy instead as per documentation, thanks! 

For the affected machine, running the group policy script should finish the onboarding step and the machine should be good to go.

**Comment by yllekz** [comment]
The .cmd script isn't interactive if the pause/confirm statements are removed. Our org is not in a position to deploy this via GPOs and we need the script method to function.

**Comment by pahuijbr** [comment]
Hi, please do not modify the onboarding scripts. The script marked for use with group policy can be used as-is, even if not deployed through group policy. Do not use the “local” onboarding script for anything other than manual, interactive deployment.
