### ISSUE TITLE
Script installing MDE GUI on server 2016 (Not recommended by Microsoft)

### ISSUE THREAD

**Issue by mattcampbell15** [microsoft/mdefordownlevelserver#22]
Hi,

During the installation of MDE on server 2016 , the scripts install the GUI, according to Microsoft docs its not recommended to install the GUI. Is it possible to modify the script to either not include it or a switch to prevent the installation?

In addition, the user interface on Windows Server 2016 only allows for basic operations. To perform operations on a device locally, refer to [Manage Microsoft Defender for Endpoint with PowerShell, WMI, and MPCmdRun.exe](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-mde-post-migration-other-tools). As a result, features that specifically rely on user interaction, such as where the user is prompted to make a decision or perform a specific task, may not work as expected**. It's recommended to disable or not enable the user interface nor require user interaction on any managed server as it may impact protection capability.**

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide

**Comment by tcoserea-msft** [comment]
_By default_, Server 2016 comes with the mentioned GUI and Install.ps1 script restores the defaults when it can, and it does so only when the feature was _disabled_ . 
On the other hand, users have the freedom to configure all optional features themselves if they choose to, so it is still possible to have it the way they like it and still use Install.ps1.
