### ISSUE TITLE
Script fails to get file version info 

### ISSUE THREAD

**Issue by FristVoid** [microsoft/mdefordownlevelserver#23]
We've observed that the getversioninfo function sometimes fails:

Exception calling "GetVersionInfo" with "1" argument(s): "C:\Windows\system32\ntoskrnl.exe"
At C:\temp\mdefordownlevelserver-main\mdefordownlevelserver-main\Install.ps1:300 char:5
+     $versionInfo = [Diagnostics.FileVersionInfo]::GetVersionInfo($Fil ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

This is 2016 build 14393.2248

**Comment by tcoserea-msft** [comment]
Should be fixed as 4/12/2023, the reason being that _sometimes_ a 32-bit Powershell was used to invoke Install.ps1 script instead of 64-bit one.
