### ISSUE TITLE
ERR_CONFLICTING_APPS

### ISSUE THREAD

**Issue by HelloThereImTom** [microsoft/mdefordownlevelserver#24]
Hi,

my customer wants to use a 3rd party EDR and MDE as AV. I see there is a CONFLICTING_APPS error message for this script.

as for the linux counterpart 
https://github.com/microsoft/mdatp-xplat/tree/master/linux/installation

There it is possible to skip the check for conflicting apps (-x parameter).

Is such a skip for conflicting apps already in place for this installer script or is it planned to have this feature in the future?

**Comment by tcoserea-msft** [comment]
Neither Install.ps1 nor md4ws.msi check for any conflicting apps for supported SKUs (Server 2012 R2 or Server 2016). 

CONFLICTING_APPS appears once in Install.ps1 to make sure we have consistent error codes when possible.
