### ISSUE TITLE
InterCa.crt is not the one the install.ps1 got signed with

### ISSUE THREAD

**Issue by snoopotic** [microsoft/mdefordownlevelserver#26]
Hi,
we cannot run install.ps1 with ExecutionPolicy RemoteSigned  / AllSigned as we do not have the signing certificate. 
Sadly the Certificate provided in this Repository is not the one this ps1 got signed. 
Can you provide the signer certificate to add it to our truststore?
Thank you

**Comment by tcoserea-msft** [comment]
You could use install.ps1 signature to install the root certificate. Simply click Properties in Explorer over Install.ps1, select "Digital Signatures" => "View Certificate" => "Install Certificate".
