### ISSUE TITLE
.etl log file can not be deleted.

### ISSUE THREAD

**Issue by lxdfly** [microsoft/mdefordownlevelserver#27]
I executed the commmand` .\Install.ps1 -OnboardingScript .\WindowsDefenderATPOnboardingScript.cmd` successfully.  But the generated .etl log file is very large (over 66GB) and can not be deleted. The error message as below:
`del : Access is denied

At line:1 char:1

+ del install-HOSTNAME-10.0.14393.5501.etl

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : PermissionDenied: (C:\win2016_onbo…14393.5501.etl:String) [Remove-Item], Unauthorized

AccessException

+ FullyQualifiedErrorId : ItemExistsUnauthorizedAccessError,Microsoft.PowerShell.Commands.RemoveItemCommand`

How can I delete it ?

**Comment by lxdfly** [comment]
> I executed the commmand` .\Install.ps1 -OnboardingScript .\WindowsDefenderATPOnboardingScript.cmd` successfully. But the generated .etl log file is very large (over 66GB) and can not be deleted. The error message as below: `del : Access is denied
> 
> At line:1 char:1
> 
> * del install-HOSTNAME-10.0.14393.5501.etl
> * ```
>   
>   ```
> * CategoryInfo : PermissionDenied: (C:\win2016_onbo…14393.5501.etl:String) [Remove-Item], Unauthorized
> 
> AccessException
> 
> * FullyQualifiedErrorId : ItemExistsUnauthorizedAccessError,Microsoft.PowerShell.Commands.RemoveItemCommand`
> 
> How can I delete it ?

The .etl log file disappeared after I restart the system, and the disk space is freed. So this issue was resolved.

**Comment by tcoserea-msft** [comment]
As administrator, run "logman -ets" to figure out the session name (it should start with "install-") that is still active (and logging inside the problematic etl) and after that "logman stop -n <sessionName> -ets" to stop the ETW session. After that you should be able to delete the .etl file.
