### ISSUE TITLE
Script requires a writeable $PSScriptRoot when logging disabled

### ISSUE THREAD

**Issue by lazynooblet** [microsoft/mdefordownlevelserver#31]
We don't want to open a writeable network share to onboard our servers, so we are running with the -NoMSILog and -NoEtl parameters.

However the script has hard-encoded test for writeable script directory.

This test should first check if it is required.

**Comment by tcoserea-msft** [comment]
Fixed with version 1.0.20230713-7A2876F7.

Thank you for reporting it.
