### ISSUE TITLE
The Onboarding script

### ISSUE THREAD

**Issue by Tarjei-stavanger** [microsoft/mdefordownlevelserver#35]
It would be helpfull if the onboarding script without a path was searched for in the directory where the install.ps1 script resides. It would make the command line less messy.

I would also like there to be a separate log directory. Logging in the same directory as the files resides is messy.

I appreciate that the scripts leave no error messages in the event log if the operating system is not correct.

**Comment by tcoserea-msft** [comment]
About relative paths - this is the current design - please full paths regardless of how messy the command line looks.
Second issue, you could copy Install.ps1 and the msi in any directory you like and have it your way. We needed a simple and intuitive way to explain to everybody where the logs are generated.
For the last comment, this is done by msiexec.exe (during installation of md4ws.msi) and not directly by Install.ps1.
