### ISSUE TITLE
negative error codes from updateplatform.exe run

### ISSUE THREAD

**Issue by Tarjei-stavanger** [microsoft/mdefordownlevelserver#36]
In the updateplatform.exe log file in `C:\Windows\temp` we have the following line 
`ERROR 0x80501005 : Failed to update platform from C:\Users\ADMINI~1.SVG\AppData\Local\Temp\C825D6EC-36AD-4487-968D-FBA1B9B06AB9`

The error reported by install.ps1 is
`Command "UpdatePlatform.exe" failed with error -2142236667 after 00:00:04.2079816`

We usually get better results from google with the hexadecimal error than decimal.

BTW. In this case there is no useful information to be found since the error appears to be very rare.

**Comment by tcoserea-msft** [comment]
It bothers me too, but the value is the same regardless of the representation base.
