### ISSUE TITLE
Install.ps1 needs adjustment for latest OnboardingScript and Offboarding

### ISSUE THREAD

**Issue by Theetjuh** [microsoft/mdefordownlevelserver#38]
line 570:  `$_ -match 'reg\s+add\s+"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Advanced Threat Protection"\s+\/v\s+OnboardingInfo'`
line 593: `$_ -match 'reg\s+add\s+"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Advanced Threat Protection"\s+\/v\s+696C1FA1-4030-4FA4-8713-FAF9B2EA7C0A'`

Change `reg\s` into `reg.exe\s` and it works again.

**Comment by tcoserea-msft** [comment]
fixed today.
