### ISSUE TITLE
Uninstall MMA

### ISSUE THREAD

**Issue by James3UK** [microsoft/mdefordownlevelserver#5]
Hi,
It would be great if the script could have an option to support uninstalling MMA (Mictosoft Monitoring Agent) where there are no workspaces present.
The -RemoveMMA flag doesn't seem to do this, maybe another flag like -UninstallMMA.

add the optional uninstall commang e.g
`MsiExec.exe /x "{774E20C6-9B94-48F2-99C9-8E1FAE17C960}" /qn`
Would need to get the correct uninstall string,
e.g {88EE688B-31C6-4B90-90DF-FBB345223F94}
Thanks

**Comment by pahuijbr** [comment]
This is deliberate as the MMA is an agent that can be used for a variety of purposes outside of Microsoft Defender for Endpoint.
