### ISSUE TITLE
For mass deployment scenarios handle errors without failing e.g where a workspace doesn't exist and -removeMMA is specified

### ISSUE THREAD

**Issue by James3UK** [microsoft/mdefordownlevelserver#7]
Hello,
For a mass deployment scenario it would be great if the script could handle more scenarios gracefully rather than failing.
For example, If the workspace doesn't exist then the script fails, it would be better if this could be handled gracefully and continue to execute e.g if this is a first time installation but the -removeMMA has been provided for mass deployment where there could be a mixture of situations.

In this situation if the MMA is not installed this script also fails if -removeMMA is specified, I appreciate this is by design but for again for mass deployment it maybe helpful for this type of error to be dealt with?

**Comment by James3UK** [comment]
A bit of a hack but the general idea:

`    if ($null -ne $RemoveMMA) {
        $uninstMMA = @{
            WorkingDirectory = $PSSCriptRoot
            Wait             = $true
            NoNewWindow      = $true
            PassThru         = $true
        }
        try 
        {
          Stop-Service HealthService
          $mma = New-Object -ComObject 'AgentConfigManager.MgmtSvcCfg'
          $workspaces = @($mma.GetCloudWorkspaces() | Select-Object -ExpandProperty:workspaceId)
        }
        catch
        {
            $uninstMMA.FilePath = (Get-Command 'msiexec.exe').Path
            $uninstMMA.ArgumentList = @('/x', '{774E20C6-9B94-48F2-99C9-8E1FAE17C960}','/quiet' ,'/norestart')
            $proc = Start-Process @uninstMMA
            if ($proc.ExitCode -eq 0) {
                Write-Host "uninstall successful."
            } else {
                Write-Warning "uninstall MMA returned $($proc.ExitCode)."
            }
        }
        if ($RemoveMMA -in $workspaces) {
            Write-Host "Removing cloud workspace $($RemoveMMA.Guid)..." 
            $mma.RemoveCloudWorkspace($RemoveMMA)
            $workspaces = @($mma.GetCloudWorkspaces() | Select-Object -ExpandProperty:workspaceId)
            if ($workspaces.Count -gt 0) {
                $mma.ReloadConfiguration()
            } else {
                Stop-Service HealthService
                $uninstMMA.FilePath = (Get-Command 'msiexec.exe').Path
                $uninstMMA.ArgumentList = @('/x', '{774E20C6-9B94-48F2-99C9-8E1FAE17C960}','/quiet' ,'/norestart')
                $MMAproc = Start-Process @uninstMMA
                if ($MMAproc.ExitCode -eq 0) {
                    Write-Host "uninstall successful."
                } else {
                    Write-Warning "uninstall MMA returned $($proc.ExitCode)."
                }
            }
            Write-Host "Workspace $($RemoveMMA.Guid) removed."
        } else {
            Write-Error "Invalid workspace id $($RemoveMMA.Guid)" -ErrorAction:Continue
        }
    }`

**Comment by pahuijbr** [comment]
Suggest not using the -RemoveMMA parameter to deal with this situation: when installing the new package, even if the workspace configuration is still present, we automatically transition the machine to the new sensor and the workspace is no longer used.

**Comment by lltltk** [comment]
I would like to second this request.
I wish to use this script for scenarios where the MMA agent may have been deployed with the MDE workspace, or where the MMA agent may have been deployed with another Log Analytics workspace which does not need to be removed (from MDE point of view, this would be a first-time onboard). 
The logic in this script is already well-written to cover both scenarios, and I don't want to have to implement additional logic to decide whether to invoke Install.ps1 with or without the -RemoveMMA parameter.
It would be nice to just invoke it with the -RemoveMMA parameter always, and let the script ignore the situation where that workspace does not exist.

**Comment by pahuijbr** [comment]
-removeMMA is optional; the workspace does not need to be removed. If you install leaving the workspace in place, Sense will simply stop using it.

Suggest not using this option for mass deployment if the existing situation is unknown. To perform cleanup, suggest uninstalling the MMA instead if no other workspaces are used (for other purposes).
