### ISSUE TITLE
Explicitly use or support TLS1.2

### ISSUE THREAD

**Issue by James3UK** [microsoft/mdefordownlevelserver#8]
On systems with TLS1.0 disabled I am getting this error:

```
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At line:2 char:46
+ ... n = ([xml]((Invoke-WebRequest -UseBasicParsing -Uri:"$uri&action=info ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```

Adding the following line allows this to work:
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

From Microsoft page:

https://docs.microsoft.com/en-us/security/engineering/solving-tls1-problem
> 
Windows PowerShell uses .NET Framework 4.5, which does not include TLS 1.2 as an available protocol. To work around this, two solutions are available:

> 1.  Modify the script in question to include the following:
>     [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
> 
> 2.  Add a system-wide registry key (e.g. via group policy) to any machine that needs to make TLS 1.2 connections from a .NET app. This will cause .NET to use the "System Default" TLS versions which adds TLS 1.2 as an available protocol AND it will allow the scripts to use future TLS Versions when the OS supports them. (e.g. TLS 1.3)  
> 
>     reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:64
> 
>     reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:32

**Comment by pahuijbr** [comment]
This should be resolved in the latest version
