### ISSUE TITLE
'MDE should be offboarded before uninstall' error message

### ISSUE THREAD

**Issue by MarcVndrhgn** [microsoft/mdefordownlevelserver#9]
I had to migrate 5 Windows 2016 servers, 4 machines where migrated successfully with the script.
One machine is exiting with : 
D:\Sources\mdefordownlevelserver-main\Install.ps1 : install exitcode: 1603.
At line:1 char:1
+ .\Install.ps1 -OnboardingScript ".\WindowsDefenderATPOnboardingScript ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install.ps1

Checking the MSI log file I can see : 
MSI (s) (F8:08) [14:12:24:481]: Product: Microsoft Defender for Endpoint -- MDE should be offboarded before uninstall

Any idea what the problem can be ?
Thanks

**Comment by pahuijbr** [comment]
2 likely possibilities:

1. These are not 2016 machines (but SAC eg 1803 etc or even 2019), the installer was not needed as the components are already in the OS, the onboarding script succeeded & the machine is now in a good state
2. Installation failed for unknown reasons and tried to roll back. Suggest cleaning "Windows Advanced Threat Protection" registry entries as appropriate, and try installing again with the latest script AND md4ws.msi package downloaded from the portal

**Comment by pahuijbr** [comment]
Adding here, this is likely the installer trying to uninstall to "clean up", then install again. 

Please attempt to use the latest MSI and install script. If the problem persists, workaround is to remove the registry information (HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection).

**Comment by yllekz** [comment]
I'm getting exit code 1603 on a 2012 R2 system with all prerequisites fulfilled and registry information cleared out. Is there any further documentation that can discuss how to get past this? The script and logs do not really explain what is happening.

**Comment by MarcVndrhgn** [comment]
Hello,
For the 2016 server, fortunately it was a test server because our only option was to destroy it and recreate it.
Now we have the exact same problem on 2012 R2 servers.
The onboarding script gives the error 1603. MDE is installed but cannot be removed 'MDE should be offboarded before uninstall'.
I have tried to run the offboarding script who returns 'Successfully offboarded machine from Microsoft Defender for Endpoint' but MDE cannot still be uninstalled.
Removing the info from the registry doesn't change anything, same error.
Running the MDE client Analyzer gives this error 'Device is running with an old version of the Microsoft Defender for Endpoint EDR sensor' but when you run the file to update the sensor it returns  'No products found to update.'
What are the options here ?
